server {
    listen 80;
    server_name averra.network;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name averra.network;

    ssl_certificate /etc/letsencrypt/live/averra.network/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/averra.network/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # Kill cache for index.html so SPAs update immediately
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /auth/ {
        proxy_pass http://api:8000/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /v1/ {
        proxy_pass http://api:8000/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
